package com.khushi.myvending;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.khushi.myvending.AdminUserGroup;
import com.khushi.myvending.AdminUserGroupRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
private AdminUserGroupRepository adminusergroupRepository;
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<AdminUserGroup> getAllAdminUsersGroup() {
		// This returns a JSON or XML with the users
		return adminusergroupRepository.findAll();
	}

}
